#@format
URL: "http://islandlives.hp1.islandarchives.ca"

# Regex pattern used to manipulate the assets url so they can be found in PATH.localAssets
REGEX: 'http.*themes\/ilives\/((css)|(js))'

PORT: 8000

PATHS:
    # Paths to Sass libraries, which can then be loaded with @import
    sass_includes:
        - 'bower_components/normalize.scss/sass'
        - 'bower_components/foundation-sites/scss'
        - 'bower_components/motion-ui/src'
    # directories to be made available to BrowserSync proxy
    localAssets:
        - 'css'
        - 'js'
        - 'mockups'
        - 'bower_components'
        - 'lib'
    #Browsersync can watch your files as you work. 
    #Changes you make will either be injected into the page (CSS & images)
    #or will cause all browsers to do a full-page refresh.
    images: 
        source: 'img-src/*'
        destination: 'images'

    mainFiles:
        - 'css/app.css'
        - 'js/app.js'
          
    sassWatch: 'scss/**/*.scss'

    # just watch these for changes and reload browser (no processing)
    reloadFiles:
        - 'js/app.js'
        - 'mockups/*.html'
          
